development:
  adapter: mysql2
  database: wegoapp
  username: root
  password: root1234
  hostname: wego.coshj9zlqcxd.ap-southeast-1.rds.amazonaws.com
  port: 3306

test:
  adapter: mysql2
  database: wegoapp
  username: root
  password: root1234
  hostname: wego.coshj9zlqcxd.ap-southeast-1.rds.amazonaws.com:3306
  port: 3306

production:
  adapter: mysql2
  database: <%= ENV['DB_SCHEMA'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  hostname: <%= ENV['DB_HOST'] %>
  port: 3306